[xdrive]
    dir = "/tmp/wetestdata/xdrive"
    host = [ "localhost:31416" ]

[[xdrive.mount]]
name = "fs" 
scheme = "nfs"
root = "/tmp/wetestdata/xdrive/data"
conf = ""

[[xdrive.mount]]
name = "myx"
scheme = "fsplugin"
root = "/tmp/wetestdata/xdrive/data"
conf = "" 
